### ISSUE TITLE
Results are bad after Optimization

### ISSUE THREAD

**Issue by xcreateadmin** [kiri-art/docker-diffusers-api-build-download#1]
Basically, when a model I use the model on [fast-Colab-A1111](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb) the results are much better when I use it on Banana using these diffusers.

Model I am using: [HF Model](https://huggingface.co/rdcoder/rd-model-test-v2)

Example of Exactly the Same Prompt with Exact same settings :

Original Model:

![grid-0001](https://user-images.githubusercontent.com/103753043/215537498-556a07e0-e4e2-48e0-9c4a-74ba97e9d613.png)

![grid-0002-2](https://user-images.githubusercontent.com/103753043/215537560-68dd44bf-e710-491e-95f5-167f6797911f.png)

Best results I got get after multiple tries using docker-diffusers-api-build-download:

![1](https://user-images.githubusercontent.com/103753043/215535198-15bcdfaa-5480-4369-a569-a4fe3fbbf792.png)

![2](https://user-images.githubusercontent.com/103753043/215535218-91732ea8-5f56-497f-8b93-5932a5bc5f76.png)

I tried all schedulers, different steps, with fp16 and without fp16 and the conclusion is the same this docker-based Rest API model results are not as accurate as SD web UI or on Hugging Face Spaces.

Is there an issue with the Optimization that you use? 
Is there a way to avoid optimization at the docker run, I think it will take more GPU memory and Power but the Results will be better I guess.

**Comment by gadicc** [comment]
Hey, the optimization is opt-in, so unless you already ran your model through it and saved it to S3 storage, you're not using it.  But in any event, the optimization is actually just saving the model in a format that's quicker to load, it doesn't modify the model at all.

I'd like to take a look at this (and hope to have a chance tomorrow) but in the meantime, I'd be grateful for the exact prompt, negative prompt (if any), seed, scheduler and image (and anything else you set) from the colab and from docker-diffusers-api to compare to.  As a general note though, docker-diffusers-api is just a wrapper around HuggingFace's diffusers library, so there could be an issue there, or different defaults for some options... most common cause though is the use of prompt weights with the default pipelines (in case that's relevant).  But let's see.

**Comment by xcreateadmin** [comment]
Sure,

Dockerfile:

```
ARG MODEL_ID="rdcoder/rd-model-test-v2"
ENV MODEL_ID=${MODEL_ID}
ARG HF_MODEL_ID=""
ENV HF_MODEL_ID=${HF_MODEL_ID}
ARG MODEL_PRECISION=""
ENV MODEL_PRECISION=${MODEL_PRECISION}
ARG MODEL_REVISION="main"
ENV MODEL_REVISION=${MODEL_REVISION}
```


To run it I am using [test.py](https://github.com/kiri-art/docker-diffusers-api/blob/dev/test.py)  from https://github.com/kiri-art and [banana.dev](https://app.banana.dev/) GPU

Run Command:

`python test.py --banana --xmfe=0 txt2img `                      

Prompts:

```
test(
    "txt2img",
    {
        "modelInputs": {
            "prompt": "car in flat icon style",
            "num_inference_steps": 60,
            "num_images_per_prompt": 4,
            "guidance_scale": 7,
        },
        "callInputs": {
            "MODEL_ID": "rdcoder/rd-model-test-v2", 
            "PIPELINE": "StableDiffusionPipeline",  
            "SCHEDULER": "EulerAncestralDiscreteScheduler",   
            "xformers_memory_efficient_attention": True,   
        },
    },
)
```

```
test(
    "txt2img",
    {
        "modelInputs": {
            "prompt": "wine glass in flat icon style",
            "num_inference_steps": 60,
            "num_images_per_prompt": 4,
            "guidance_scale": 7,
        },
        "callInputs": {
            "MODEL_ID": "rdcoder/rd-model-test-v2", 
            "PIPELINE": "StableDiffusionPipeline",            
            "SCHEDULER": "EulerAncestralDiscreteScheduler",  
            "xformers_memory_efficient_attention": False,  
        },
    },
)
```
**Original Model:**

<img width="1440" alt="Screenshot 2023-01-31 at 10 19 06 AM" src="https://user-images.githubusercontent.com/103753043/215668204-7b8de8bc-0027-4b51-8c46-45a08d17cbda.png">

**docker-diffuser Implementation:**

![Untitled design](https://user-images.githubusercontent.com/103753043/215666526-cba5b988-4d63-4fe8-a793-125be63effc9.png)

> There are a few more images in the original issue message as well for Wine and Car prompts.

I also tried these schedulers:

`DPMSolverMultistepScheduler`,` LMSDiscreteScheduler`,  `DDIMScheduler`, `PNDMScheduler`, `EulerAncestralDiscreteScheduler`, `EulerDiscreteScheduler`,
Tried with `xformers_memory_efficient_attention` `True` and `False` and even tested with other models, and all these tests had bad results.

If Optimization is Opt-in why does banana.dev logs say this:

```
WARNING: Image Optimization Failed - cold boots may be slow. Optimization logs follow:
Couldn't tag image:
 : {"stream":"\u001b[91mERROR conda.cli.main_run:execute(47): `conda run /bin/bash -c python3 compiler.py` failed. (See above for error)\n\u001b[0m"}
```

I have also tested old versions of [docker-diffusers-api](https://github.com/kiri-art/docker-diffusers-api). Same issue with that as well.

I would really appreciate any help you can provide.

**Comment by gadicc** [comment]
Thanks for all the details, that's really helpful.  Last thing I need is just a seed with pics from both AUTOMATIC1111 and diffusers using the same seed.

Banana's optimization unfortunately is not opt-in or opt-out (I wish they'd provide such an option), but since docker-diffusers-api does some things that breaks it anyway, you can see even Banana's optimization isn't being used here.

Thanks again for the detailed report, I'd love to get to the bottom of this.  Kind of also wondering if it could be a PNG compression issue and I'll look into that too.  Thanks :D

**Comment by xcreateadmin** [comment]
Sure, Thanks for looking into this.

Seed: 2974676885

Prompt: car in flat icon style

Settings: 
```
"num_inference_steps": 60,
"num_images_per_prompt": 4,
"guidance_scale": 7,
"SCHEDULER": "EulerAncestralDiscreteScheduler",
"seed": 2974676885,
```

AUTOMATIC1111:


![1](https://user-images.githubusercontent.com/103753043/215713923-369f4457-bb5b-4d80-8b72-98396fe05e80.png)

![2](https://user-images.githubusercontent.com/103753043/215713950-63e25bde-863f-4f31-856c-48da697efb74.png)


![3](https://user-images.githubusercontent.com/103753043/215713976-31f259be-c6f5-4010-91de-599182ab6776.png)

![4](https://user-images.githubusercontent.com/103753043/215714013-721cb91f-db0d-4170-b226-33b79433517a.png)


Diffusers:

![txt2img_0](https://user-images.githubusercontent.com/103753043/215714106-e6e6f2a9-df53-4c71-82da-a4b822f8657a.png)

![txt2img_1](https://user-images.githubusercontent.com/103753043/215714140-4f791b0b-503e-4652-b237-ec9b6b9fbcb2.png)

![txt2img_2](https://user-images.githubusercontent.com/103753043/215714192-4215efbd-30e8-41e5-af31-5b0125491283.png)

![txt2img_3](https://user-images.githubusercontent.com/103753043/215714223-893aaf20-9dcd-44a6-855b-8f39f0cc97b4.png)



As you can see it's not just that quality is different since A1111 is 512 pixel and Diffuser is 256 pixel but the overall design in more accurate, clean and real like in A1111 compared to diffusers.

**Comment by gadicc** [comment]
Oh, I didn't actually notice before that the diffusers images were 256x256, thanks for clarifying.  That's beyond a scaling issue, if you generate pictures at a very different resolution to the original model, the results will almost always be much poorer, because the model is trained on images on a specific size, and trained to produce images of a specific size (which is why generating an image at the model's resolution, and then upscaling afterwards, produces much better results than trying to generate a high resolution image from the beginning; but changing just the width or height only can be useful to produce non-square images).

In any event, I was able to reproduce your exact diffusers results above.  When adding modelInputs `{ width: 512, height: 512 }`, and with the same seed, I got the following, which I believe is an exact match to your output from AUTOMATIC1111, right?

![txt2img_0](https://user-images.githubusercontent.com/381978/215833690-ab00b7f2-a849-4849-ae9d-118b1140c95c.png)

unfortunately for the additional images, the way diffusers and AUTOMATIC1111 changes the seed after each generation differs, so I couldn't compare, but, here they are anyway from the diffusers side:

![txt2img_1](https://user-images.githubusercontent.com/381978/215834279-3a7add3f-6323-45e7-a150-41a9b8fb4434.png)

![txt2img_2](https://user-images.githubusercontent.com/381978/215834299-32a3e7a1-9bf0-4824-b032-775dd366eddb.png)

![txt2img_3](https://user-images.githubusercontent.com/381978/215834330-7fde0f66-e1fd-455e-ba3e-587b73a99917.png)

What do you think?

**Comment by gadicc** [comment]
For reference also here were my test cases:

```bash
# Produced the same results as what you sent (for diffusers)
$ python test.py txt2img --call-arg MODEL_ID="rdcoder/rd-model-test-v2" --call-arg MODEL_URL="s3://" --call-arg MODEL_PRECISION="fp16" --model-arg num_inference_steps=60 --model-arg num_images_per_prompt=4 --model-arg guidance_scale=7 --call-arg SCHEDULER="EulerAncestralDiscreteScheduler" --model-arg seed=2974676885 --model-arg prompt="car in flat icon style"
Running test: txt2img
{
    "modelInputs": {
        "prompt": "car in flat icon style",
        "num_inference_steps": 60,
        "num_images_per_prompt": 4,
        "guidance_scale": 7,
        "seed": 2974676885
    },
    "callInputs": {
        "MODEL_ID": "rdcoder/rd-model-test-v2",
        "MODEL_URL": "s3://",
        "MODEL_PRECISION": "fp16",
        "SCHEDULER": "EulerAncestralDiscreteScheduler"
    }
}

Request took 331.6s (init: 0ms, download: 4.1m, compress: 8.8s, upload: 12.0s, inference: 47.5s)
Saved ./tests/output/txt2img_0.png
Saved ./tests/output/txt2img_1.png
Saved ./tests/output/txt2img_2.png
Saved ./tests/output/txt2img_3.png

{
    "$meta": {
        "PIPELINE": "StableDiffusionPipeline"
    },
    "images_base64": [
        "[256x256 PNG image, 44.9KiB bytes]",
        "[256x256 PNG image, 44.2KiB bytes]",
        "[256x256 PNG image, 40.8KiB bytes]",
        "[256x256 PNG image, 41.0KiB bytes]"
    ],
    "$timings": {
        "init": 0,
        "download": 245502,
        "compress": 8782,
        "upload": 12041,
        "inference": 47450
    },
    "$mem_usage": 0.7343139095843794
}
```

```bash
# Produced the matching first image with AUTOMATIC1111 and the additional images I sent
$ python test.py txt2img --call-arg MODEL_ID="rdcoder/rd-model-test-v2" --call-arg MODEL_URL="s3://" --call-arg MODEL_PRECISION="fp16" --model-arg num_inference_steps=60 --model-arg num_images_per_prompt=4 --model-arg guidance_scale=7 --call-arg SCHEDULER="EulerAncestralDiscreteScheduler" --model-arg seed=2974676885 --model-arg prompt="car in flat icon style" --model-arg width=512 --model-arg height=512
Running test: txt2img
{
    "modelInputs": {
        "prompt": "car in flat icon style",
        "num_inference_steps": 60,
        "num_images_per_prompt": 4,
        "guidance_scale": 7,
        "seed": 2974676885,
        "width": 512,
        "height": 512
    },
    "callInputs": {
        "MODEL_ID": "rdcoder/rd-model-test-v2",
        "MODEL_URL": "s3://",
        "MODEL_PRECISION": "fp16",
        "SCHEDULER": "EulerAncestralDiscreteScheduler"
    }
}

Request took 163.0s (inference: 2.7m)
Saved ./tests/output/txt2img_0.png
Saved ./tests/output/txt2img_1.png
Saved ./tests/output/txt2img_2.png
Saved ./tests/output/txt2img_3.png

{
    "$meta": {
        "PIPELINE": "StableDiffusionPipeline"
    },
    "images_base64": [
        "[512x512 PNG image, 82.9KiB bytes]",
        "[512x512 PNG image, 100.9KiB bytes]",
        "[512x512 PNG image, 65.3KiB bytes]",
        "[512x512 PNG image, 100.2KiB bytes]"
    ],
    "$timings": {
        "inference": 162994
    },
    "$mem_usage": 0.4090008608413719
}
```

**Comment by xcreateadmin** [comment]
Oh, I thought Images were created in 512 but then compressed to 256 by the diffuser 😅.

Yeah, you are absolutely right, since it's trained at 512 x 512 px it works best only for that size.

I didn't know you could pass `width` and `height` as `ModelInputs`.

A small suggestion would be to add all possible model inputs and call inputs in `readme.md`

Thanks for the help ✌️

**Comment by gadicc** [comment]
My pleasure!  Glad you're up and running in full quality :)  And thanks for reporting back.

So uhh.... the [example](https://github.com/kiri-art/docker-diffusers-api#usage) in the readme does mention `width` and `height` :sweat_smile: 

However, I did clean up the section directly below that to give a bit more info on how we wrap the diffusers library and how to find which options are available.  So thanks for the nudge :)  Let me know if it's not clear.

Happy diffusing! :firecracker: :tada:
